id = "just"
name = "Justfile"
description = "Justfile syntax highlighting"
version = "1.0.0"
schema_version = 1
authors = ["Jack T <jack@jackt.space>"]
repository = "https://github.com/jackTabsCode/zed-just"

[grammars.just]
repository = "https://github.com/IndianBoy42/tree-sitter-just"
commit = "792717c262df6d6fa285c1136a11c23cedadcb0c"
