id = "just"
name = "Justfile"
description = "Justfile language support"
version = "0.2.0"
schema_version = 1
authors = [
  "Jack Taylor <j@jackt.io>",
  "Matt Robenolt <m@robenolt.com>",
]
repository = "https://github.com/jackTabsCode/zed-just"

[grammars.just]
repository = "https://github.com/mattrobenolt/tree-sitter-just"
rev = "a2e0c786fa90ac1e85dc40708b2ab277c007f55e"

[language_servers.just-lsp]
name = "just-lsp"
languages = ["Just"]
