name = "Just"
grammar = "just"
path_suffixes = ["justfile", "Justfile", "JUSTFILE", "just"]
first_line_pattern = '^#!.*\b(?:just)\b'
line_comments = ["# "]
brackets = [{ start = "(", end = ")", close = true, newline = true }]

[formatter]
language_servers = ["just-lsp"]
